name: NeoForge Build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21 # NeoForge requiere Java 21 para versiones actuales
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          # Esto ayuda a que la compilación sea más rápida las siguientes veces
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build with Gradle
        # Usamos --no-daemon para que sea más estable en servidores virtuales
        run: ./gradlew build --no-daemon

      - name: Upload Mod Jar
        uses: actions/upload-artifact@v4
        with:
          name: NeoForge-Mod-Output
          # NeoForge genera varios archivos, esto filtrará solo el principal
          path: |
            build/libs/*.jar
            !build/libs/*-sources.jar
            !build/libs/*-javadoc.jar
            !build/libs/*-dev.jar
